// backend/src/routes/authRoutes.js
const express    = require("express");
const bcrypt     = require("bcryptjs");
const jwt        = require("jsonwebtoken");
const supabase   = require("../config/supabaseClient"); // DB generates user_id

const router     = express.Router();
const JWT_SECRET = process.env.JWT_SECRET;

/**
 * POST /api/auth/register
 */
router.post("/register", async (req, res) => {
  try {
    const { email, password, username } = req.body;
    if (!email || !password || !username) {
      return res.status(400).json({ error: "Email, password, and username are required" });
    }

    const trimmedEmail = email.trim().toLowerCase();
    const trimmedUsername = username.trim();

    // Check if user with this email or username already exists
    const { data: existingUser, error: fetchError } = await supabase
      .from("user_profile")
      .select("user_id")
      .or(`email.eq.${trimmedEmail},username.eq.${trimmedUsername}`)
      .maybeSingle();

    if (fetchError) {
      console.error("Fetch-existing-user error during registration:", fetchError);
      return res.status(500).json({ error: "Database error checking existing user." });
    }
    if (existingUser) {
      return res.status(409).json({ error: "User with this email or username already exists." });
    }

    const password_hash = await bcrypt.hash(password, 10);

    const newUserProfile = {
      // user_id is generated by DB
      username: trimmedUsername,
      password: password_hash, // This is the hashed password
      email: trimmedEmail,
      created_at: new Date().toISOString(),
      // bio and profile_picture_url can be added/updated later by the user
      // No global 'role' field in user_profile schema provided
    };

    const { data: insertedUser, error: insertError } = await supabase
      .from("user_profile")
      .insert(newUserProfile)
      .select('user_id, username, email, profile_picture_url, created_at, bio') // Removed 'role'
      .single();

    if (insertError) {
      console.error("Supabase insert user_profile error:", insertError);
      if (insertError.code === '23505') { 
          return res.status(409).json({ error: "A user with these details already exists (unique constraint)."});
      }
      return res.status(500).json({ error: `Failed to register user: ${insertError.message}` });
    }
    if (!insertedUser || !insertedUser.user_id) {
      return res.status(500).json({ error: "Failed to register user (no user_id returned after insert)." });
    }

    // JWT Payload: keep it minimal. Middleware will fetch community roles as needed.
    const token = jwt.sign(
      { userId: insertedUser.user_id, email: insertedUser.email },
      JWT_SECRET,
      { expiresIn: "2h" } 
    );

    return res.status(201).json({ user: insertedUser, token });

  } catch (err) {
    console.error("Register Endpoint Error (unexpected):", err);
    return res.status(500).json({ error: "An unexpected error occurred during registration." });
  }
});

// Login route remains largely the same, just ensure it doesn't expect a global role from user_profile
router.post("/login", async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) {
      return res.status(400).json({ error: "Email and password are required" });
    }

    const trimmedEmail = email.trim().toLowerCase();

    const { data: userProfile, error: fetchError } = await supabase
      .from("user_profile")
      .select("user_id, username, email, password, profile_picture_url, created_at, bio") // Removed 'role'
      .eq("email", trimmedEmail)
      .single();

    if (fetchError || !userProfile) {
      return res.status(401).json({ error: "Invalid credentials or user not found." });
    }

    const validPassword = await bcrypt.compare(password, userProfile.password);
    if (!validPassword) {
      return res.status(401).json({ error: "Invalid credentials." });
    }

    const token = jwt.sign(
      { userId: userProfile.user_id, email: userProfile.email },
      JWT_SECRET,
      { expiresIn: "2h" }
    );

    const { password: _, ...safeUser } = userProfile; 

    return res.json({ user: safeUser, token });

  } catch (err) {
    console.error("Login Endpoint Error (unexpected):", err);
    return res.status(500).json({ error: "An unexpected error occurred during login." });
  }
});

module.exports = router;
