// backend/src/routes/communityPostRoutes.js
const express = require("express");
const supabase = require("../config/supabaseClient");
const { checkJwtMiddleware } = require("../middleware/authMiddleware");

const router = express.Router();

/**
 * GET /api/community-posts?communityId=:communityId
 * Fetches posts for a specific community.
 */
router.get("/", async (req, res) => {
    const { communityId } = req.query;

    if (!communityId) {
        return res.status(400).json({ error: "Community ID is required." });
    }

    try {
        const { data: posts, error } = await supabase
            .from("community_post")
            .select(`
                post_id,
                community_id,
                user_id,
                title,
                content,
                created_at,
                upvote_count,
                downvote_count,
                user_profile (
                    username,
                    profile_picture_url
                )
            `)
            .eq("community_id", communityId)
            .order("created_at", { ascending: false });

        if (error) {
            console.error("Fetch Community Posts Error:", error);
            return res.status(500).json({ error: "Failed to retrieve community posts." });
        }
        res.json({ posts: posts || [] });
    } catch (err) {
        console.error("Fetch Community Posts Unexpected Error:", err);
        res.status(500).json({ error: "An unexpected error occurred." });
    }
});

/**
 * POST /api/community-posts
 * Creates a new post within a community.
 * Requires community_id in the body. User ID comes from JWT.
 */
router.post("/", checkJwtMiddleware, async (req, res) => {
    const { community_id, title, content } = req.body;
    const user_id = req.userId; // from JWT middleware

    if (!community_id || !title || !content) {
        return res.status(400).json({ error: "Community ID, title, and content are required." });
    }
    if (!title.trim() || !content.trim()) {
        return res.status(400).json({ error: "Title and content cannot be empty." });
    }
    
    // Basic UUID validation for community_id
    const uuidRegex = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/;
    if (!uuidRegex.test(community_id)) {
        return res.status(400).json({ error: "Invalid community_id format." });
    }

    try {
        // Optional: Check if user is a member of the community before allowing post
        const { data: membership, error: membershipError } = await supabase
            .from('community_membership')
            .select('user_id')
            .eq('community_id', community_id)
            .eq('user_id', user_id)
            .maybeSingle();

        if (membershipError) {
            console.error("Create Community Post - Membership Check Error:", membershipError);
            return res.status(500).json({ error: "Error checking community membership." });
        }
        if (!membership) {
            return res.status(403).json({ error: "User is not a member of this community and cannot post." });
        }

        const newPostData = {
            // post_id is generated by DB
            community_id,
            user_id,
            title: title.trim(),
            content: content.trim(),
            created_at: new Date().toISOString(),
            // upvote_count and downvote_count default to 0 in DB schema
        };

        const { data: createdPost, error: insertError } = await supabase
            .from("community_post")
            .insert(newPostData)
            .select(`
                *,
                user_profile (
                    username,
                    profile_picture_url
                )
            `)
            .single();

        if (insertError) {
            console.error("Create Community Post - Insert Error:", insertError);
            if (insertError.code === '23503') { // Foreign key violation
                return res.status(400).json({ error: "Invalid community_id or user_id." });
            }
            return res.status(500).json({ error: `Failed to create community post: ${insertError.message}` });
        }
        if (!createdPost || !createdPost.post_id) {
            return res.status(500).json({ error: "Community post creation failed to return data or post_id." });
        }

        res.status(201).json({ post: createdPost });

    } catch (err) {
        console.error("Create Community Post - Unexpected Error:", err);
        res.status(500).json({ error: "An unexpected error occurred while creating the community post." });
    }
});

module.exports = router;
